#pragma once

namespace Client
{
	static const unsigned int g_iWinSizeX = 1280;
	static const unsigned int g_iWinSizeY = 720;

	enum LEVEL_ID { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_BOSS, LEVEL_END };
}

enum SOUND_CHANNEL
{
	SOUND_LOGO,
	SOUND_BGM,
	WARNING,
	
	PLAYER_ATTACK1,
	PLAYER_ATTACK2,
	PLAYER_ATTACK3,
	PLAYER_ATTACK4,
	PLAYER_ATTACK5,
	PLAYER_ATTACK41,
	PLAYER_ATTACK42,
	PLAYER_ATTACK43,
	PLAYER_ATTACK44,
	PLAYER_ATTACK45,
	PLAYER_ATTACK11,
	PLAYER_ATTACK21,
	PLAYER_ATTACK31,
	PLAYER_ATTACK12,
	PLAYER_ATTACK22,
	PLAYER_ATTACK32,
	DASH,
	EVOLUTION,

	THORN0,

	BOSS_BORN,
	//BOSS_EVOLUTION,
	//BOSS_CHANGE,
	//BOSS_DIE,
	//BOSS_DASH,
	//BOSS_BURROW,
	BOSS_VOICE,

	SIGNAL,
	SLOW,
	SNAP
};

extern HINSTANCE g_hInst;
extern HWND g_hWnd;

using namespace Client;